# declare Traefik deployment
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: archive-app
  labels:
    app: archive-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archive-app
  template:
    metadata:
      labels:
        app: archive-app
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-tmp
      containers:
        - name: archive-app
          image: "gcr.io/d-talks-243604/d-talks_link-archive:latest"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/data"
              name: "data"
      imagePullSecrets:
        - name: var-registry-secret
